Repository agntcy/slim, pull requests merged in 2025-09, with the labels that each got.

#633 fix(ci): python examples image build
  .github/workflows/data-plane.yaml
  .github/workflows/reusable-python-build-wheels.yaml
Labels: cicd

#650 doc(srpc-compiler): add readme
  data-plane/srpc-compiler/Cargo.toml
  data-plane/srpc-compiler/README.md
Labels: documentation

#643 chore(slimrpc): release 0.1.0
  .github/release-manifest.json
  data-plane/python/integrations/slimrpc/CHANGELOG.md
  data-plane/python/integrations/slimrpc/pyproject.toml
Labels: autorelease: pending

#639 chore(main): release slima2a 0.1.0
  .github/release-manifest.json
  data-plane/python/integrations/slima2a/CHANGELOG.md
  data-plane/python/integrations/slima2a/pyproject.toml
Labels: autorelease: pending

#516 chore(main): release control-plane 0.1.1
  .github/release-manifest.json
  control-plane/control-plane/CHANGELOG.md
Labels: autorelease: pending

#600 chore(main): release helm-slim-control-plane 0.1.4
  .github/release-manifest.json
  charts/slim-control-plane/CHANGELOG.md
Labels: autorelease: pending

#545 chore(main): release slim-testutils 0.2.2
  .github/release-manifest.json
  data-plane/testing/CHANGELOG.md
Labels: autorelease: pending

#720 chore(main): release slim-bindings-examples 0.1.1
  .github/release-manifest.json
  data-plane/python/bindings/examples/CHANGELOG.md
  data-plane/python/bindings/examples/pyproject.toml
Labels: autorelease: pending

#730 build: upgrade to rust toolchain 1.90.0
  data-plane/core/auth/src/jwt.rs
  data-plane/core/auth/src/jwt_middleware.rs
  data-plane/core/auth/src/resolver.rs
  data-plane/core/auth/src/shared_secret.rs
  data-plane/core/controller/src/service.rs
  data-plane/core/datapath/src/message_processing.rs
  data-plane/core/datapath/src/tables/subscription_table.rs
  data-plane/core/service/src/session/channel_endpoint.rs
  data-plane/core/service/src/session/interceptor_mls.rs
  data-plane/core/service/src/session/point_to_point.rs
  data-plane/core/tracing/src/lib.rs
  data-plane/rust-toolchain.toml
Labels: enhancement
