Repository agntcy/slim, pull requests merged in 2025-07, with the labels that each got.

#483 chore(main): release helm-slim-control-plane 0.1.2
  .github/release-manifest.json
  charts/slim-control-plane/CHANGELOG.md
  charts/slim-control-plane/Chart.yaml
Labels: autorelease: pending

#319 chore: release
  data-plane/Cargo.lock
  data-plane/Cargo.toml
  data-plane/core/auth/CHANGELOG.md
  data-plane/core/auth/Cargo.toml
  data-plane/core/config/CHANGELOG.md
  data-plane/core/config/Cargo.toml
  data-plane/core/controller/CHANGELOG.md
  data-plane/core/controller/Cargo.toml
  data-plane/core/datapath/CHANGELOG.md
  data-plane/core/datapath/Cargo.toml
  data-plane/core/service/CHANGELOG.md
  data-plane/core/service/Cargo.toml
  data-plane/core/signal/CHANGELOG.md
  data-plane/core/signal/Cargo.toml
  data-plane/core/slim/CHANGELOG.md
  data-plane/core/slim/Cargo.toml
  data-plane/core/tracing/CHANGELOG.md
  data-plane/core/tracing/Cargo.toml
  data-plane/integrations/mcp/mcp-proxy/Cargo.lock
  data-plane/integrations/mcp/mcp-proxy/Cargo.toml
Labels: buf skip breaking

#383 chore(main): release slimctl 0.2.0
  .github/release-manifest.json
  control-plane/slimctl/CHANGELOG.md
Labels: autorelease: pending

#341 chore(main): release slim-bindings 0.4.0
  .github/release-manifest.json
  data-plane/python-bindings/CHANGELOG.md
  data-plane/python-bindings/pyproject.toml
Labels: autorelease: pending

#495 feat(slim-helm): upgrade helm to slim image 0.4.0
  charts/slim/Chart.yaml
Labels: buf skip breaking

#498 chore(main): release slimctl 0.2.1
  .github/release-manifest.json
  control-plane/slimctl/CHANGELOG.md
Labels: autorelease: pending

#499 fix(testutils): use common dockerfile to build testutils
  .github/workflows/release-slimctl.yaml
  data-plane/Dockerfile
  data-plane/testing/Dockerfile
  docker-bake.hcl
Labels: buf skip breaking

#503 feat(slim-control-plane): upgrade chart to latest control-plane image
  charts/slim-control-plane/Chart.yaml
Labels: buf skip breaking

#504 chore(main): release helm-slim-control-plane 0.1.3
  .github/release-manifest.json
  charts/slim-control-plane/CHANGELOG.md
  charts/slim-control-plane/Chart.yaml
Labels: autorelease: pending, buf skip breaking
